steps:

# Build image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/oval-turbine-495504-h2/mydockerregistry-aditya/python-app:$BUILD_ID'
    - '.'

# Push image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/oval-turbine-495504-h2/mydockerregistry-aditya/python-app:$BUILD_ID'

images:
- 'us-central1-docker.pkg.dev/oval-turbine-495504-h2/mydockerregistry-aditya/python-app:$BUILD_ID'
